### ISSUE TITLE
[1.0] smuxi-frontend-gnome crashes on run

### ISSUE THREAD

**Issue by sagitter** [meebey/smuxi#241]
Hi all,

smuxi-frontend-gnome crashes reporting this:

```
$ smuxi-frontend-gnome 

Native stacktrace:

	mono(+0xccd20) [0x56433896ed20]
	mono(+0x4103c) [0x5643388e303c]
	/lib64/libpthread.so.0(+0x109f0) [0x7f1f830319f0]
	mono(+0x228bc8) [0x564338acabc8]
	mono(+0x22a00c) [0x564338acc00c]
	mono(+0x2310a5) [0x564338ad30a5]
	mono(+0x22a11b) [0x564338acc11b]
	mono(+0x2294c2) [0x564338acb4c2]
	mono(+0x2218c8) [0x564338ac38c8]
	mono(+0x222159) [0x564338ac4159]
	mono(+0x22b16b) [0x564338acd16b]
	mono(+0x22b293) [0x564338acd293]
	mono(+0x1ed40b) [0x564338a8f40b]
	mono(+0x1c299c) [0x564338a6499c]
	mono(+0x4236e) [0x5643388e436e]
	mono(mono_main+0x2d0) [0x564338943080]
	/lib64/libc.so.6(__libc_start_main+0xf0) [0x7f1f82a69580]
	mono(+0x37219) [0x5643388d9219]

Debug info from gdb:

[New LWP 18493]
[New LWP 18492]
[New LWP 18491]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f1f830315db in waitpid () from /lib64/libpthread.so.0
  Id   Target Id         Frame 
  4    Thread 0x7f1f7bee3700 (LWP 18491) "mono-boehm" 0x00007f1f8302db10 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  3    Thread 0x7f1f7b6e2700 (LWP 18492) "mono-boehm" 0x00007f1f8302db10 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  2    Thread 0x7f1f7aee1700 (LWP 18493) "mono-boehm" 0x00007f1f8302db10 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
* 1    Thread 0x7f1f83b41740 (LWP 18486) "mono-boehm" 0x00007f1f830315db in waitpid () from /lib64/libpthread.so.0

Thread 4 (Thread 0x7f1f7bee3700 (LWP 18491)):
#0  0x00007f1f8302db10 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000564338ad2707 in GC_wait_marker ()
#2  0x0000564338aca5a2 in GC_help_marker ()
#3  0x0000564338ad0d9f in GC_mark_thread ()
#4  0x00007f1f8302860a in start_thread () from /lib64/libpthread.so.0
#5  0x00007f1f82b4bbbd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f1f7b6e2700 (LWP 18492)):
#0  0x00007f1f8302db10 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000564338ad2707 in GC_wait_marker ()
#2  0x0000564338aca5a2 in GC_help_marker ()
#3  0x0000564338ad0d9f in GC_mark_thread ()
#4  0x00007f1f8302860a in start_thread () from /lib64/libpthread.so.0
#5  0x00007f1f82b4bbbd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f1f7aee1700 (LWP 18493)):
#0  0x00007f1f8302db10 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000564338ad2707 in GC_wait_marker ()
#2  0x0000564338aca5a2 in GC_help_marker ()
#3  0x0000564338ad0d9f in GC_mark_thread ()
#4  0x00007f1f8302860a in start_thread () from /lib64/libpthread.so.0
#5  0x00007f1f82b4bbbd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f1f83b41740 (LWP 18486)):
#0  0x00007f1f830315db in waitpid () from /lib64/libpthread.so.0
#1  0x000056433896edbd in mono_handle_native_sigsegv ()
#2  0x00005643388e303c in mono_sigsegv_signal_handler ()
#3  <signal handler called>
#4  0x0000564338acabc8 in GC_push_all_eager ()
#5  0x0000564338acc00c in GC_push_current_stack ()
#6  0x0000564338ad30a5 in GC_generic_push_regs ()
#7  0x0000564338acc11b in GC_push_roots ()
#8  0x0000564338acb4c2 in GC_mark_some ()
#9  0x0000564338ac38c8 in GC_stopped_mark ()
#10 0x0000564338ac4159 in GC_try_to_collect_inner ()
#11 0x0000564338acd16b in GC_init_inner.part.2 ()
#12 0x0000564338acd293 in GC_init ()
#13 0x0000564338a8f40b in mono_gc_base_init ()
#14 0x0000564338a6499c in mono_init_internal ()
#15 0x00005643388e436e in mini_init ()
#16 0x0000564338943080 in mono_main ()
#17 0x00007f1f82a69580 in __libc_start_main () from /lib64/libc.so.6
#18 0x00005643388d9219 in _start ()

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Zrušené (bol uložený výpis pamäte)
```

Fedora 23 64bit
Mono-4.0.5
Bug ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1266148

**Comment by meebey** [comment]
This was fixed in 1.0.1
